// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGCBssBeA07w1BA3v_FkGI76oaEdKOFSU',
    appId: '1:740662855417:web:3b8e04bb0022ed3c794428',
    messagingSenderId: '740662855417',
    projectId: 'sakura-loja',
    authDomain: 'sakura-loja.firebaseapp.com',
    storageBucket: 'sakura-loja.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5o8NlOZRCQP5P0K0CHR4rVE3Ak6CZSiA',
    appId: '1:740662855417:android:d97a48a1e7a46843794428',
    messagingSenderId: '740662855417',
    projectId: 'sakura-loja',
    storageBucket: 'sakura-loja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAq6H1YTk9hod1agg0wAZOLcV_kn5VQhU',
    appId: '1:740662855417:ios:33433bd431d38d27794428',
    messagingSenderId: '740662855417',
    projectId: 'sakura-loja',
    storageBucket: 'sakura-loja.appspot.com',
    iosBundleId: 'br.com.dtec.loja.minimalstore2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAq6H1YTk9hod1agg0wAZOLcV_kn5VQhU',
    appId: '1:740662855417:ios:33433bd431d38d27794428',
    messagingSenderId: '740662855417',
    projectId: 'sakura-loja',
    storageBucket: 'sakura-loja.appspot.com',
    iosBundleId: 'br.com.dtec.loja.minimalstore2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGCBssBeA07w1BA3v_FkGI76oaEdKOFSU',
    appId: '1:740662855417:web:d98e311877b490a3794428',
    messagingSenderId: '740662855417',
    projectId: 'sakura-loja',
    authDomain: 'sakura-loja.firebaseapp.com',
    storageBucket: 'sakura-loja.appspot.com',
  );

}